# config.py

XMPP_SERVER = "localhost"
PASSWORD = "password_super_secreta"
MAX_POWER_KW = 3.0  # Global power limit of the house for P2P negotiation

# JIDS of each agent
AGENTS = {
    "world": f"world@{XMPP_SERVER}",
    "environment": f"environment@{XMPP_SERVER}",
    "solar": f"solar@{XMPP_SERVER}",
    "battery": f"battery@{XMPP_SERVER}",
    "air_fryer": f"air_fryer@{XMPP_SERVER}",
    "fridge": f"fridge@{XMPP_SERVER}",
    "ac_livingroom": f"ac.livingroom@{XMPP_SERVER}",
    "heater_livingroom": f"heater.livingroom@{XMPP_SERVER}",
    "washing_machine": f"washing_machine@{XMPP_SERVER}",
    "dish_washer": f"dish_washer@{XMPP_SERVER}",
}

# Simulation 
SIMULATION_SPEED = 1
MINUTES_PER_STEP = 60

# Distributed P2P negotiation settings
NEGOTIATION_TIMEOUT_SEC = 5
NEGOTIATION_RETRY_LIMIT = 1
NEGOTIATION_LOOP_PERIOD_SEC = 1

# Price-aware priority settings
PRICE_MIN = 0.07   # Minimum expected electricity price (€/kWh)
PRICE_MAX = 0.27   # Maximum expected electricity price (€/kWh)

# Solar production simulation settings
SOLAR_PRODUCTION_START_HOUR = 7
SOLAR_PRODUCTION_END_HOUR = 19
SOLAR_WEATHER_FACTOR_MIN = 0.4
SOLAR_WEATHER_FACTOR_MAX = 1.2
SOLAR_PEAK_BY_SEASON_KW = {
    "summer": 1.8,
    "winter": 1.0,
    "spring": 1.1,
    "autumn": 1.2,
}

# Global Device Defaults
DEFAULT_PRIORITY = 3
DEFAULT_ENERGY_PRICE = 0.12
NEGOTIATION_JITTER_MAX = 2.0
NEGOTIATION_TIMEOUT = 10
SHED_TIMEOUT_STEPS = 4

# Air Conditioner
AC_TARGET_TEMP = 21
AC_TEMP_MARGIN = 1
AC_PRICE_SENSITIVITY = 0
AC_ACTIVE_POWER_KW = 1.5
AC_IDLE_POWER_KW = 0.0
AC_PRIORITY_THRESHOLDS = [8, 6, 4, 2] # Deviation thresholds for priority 5, 4, 3, 2

# Heater
HEATER_TARGET_TEMP = 21
HEATER_TEMP_MARGIN = 1
HEATER_PRICE_SENSITIVITY = 0
HEATER_ACTIVE_POWER_KW = 1.5
HEATER_IDLE_POWER_KW = 0.0
HEATER_PRIORITY_THRESHOLDS = [8, 6, 4, 2] # Cold deviation thresholds for priority 5, 4, 3, 2

# Air Fryer
AIR_FRYER_ACTIVE_POWER_KW = 2.0
AIR_FRYER_IDLE_POWER_KW = 0.0
AIR_FRYER_PRIORITY = 5
AIR_FRYER_CHANCE_PER_HOUR = 0.15
AIR_FRYER_CYCLE_DURATION_MINUTES = 120

# Battery
BATTERY_CAPACITY_KWH = 20.0
BATTERY_MAX_POWER_KW = 2.0
BATTERY_INITIAL_CHARGE_PERCENT = 0.5
BATTERY_SOLAR_CHARGE_START_HOUR = 7
BATTERY_SOLAR_CHARGE_END_HOUR = 12
BATTERY_DISCHARGE_START_HOUR = 13
BATTERY_DISCHARGE_END_HOUR = 18
BATTERY_PRIORITY = -100

# Dish Washer
DISH_WASHER_THRESHOLD = 20
DISH_WASHER_CYCLE_DURATION_MINUTES = 120
DISH_WASHER_PER_CYCLE = 20
DISH_WASHER_ACCUMULATION_RATE = 2
DISH_WASHER_PRICE_SENSITIVITY = 0
DISH_WASHER_ACTIVE_POWER_KW = 0.5
DISH_WASHER_IDLE_POWER_KW = 0.0
DISH_WASHER_WAITING_BONUS_DIVIDER = 3
DISH_WASHER_PRIORITY_THRESHOLDS = [40, 35, 30, 25] # Counts for priority 5, 4, 3, 2

# Refrigerator
FRIDGE_TARGET_TEMP = 4
FRIDGE_TEMP_MARGIN = 1
FRIDGE_ACTIVE_POWER_KW = 0.18
FRIDGE_IDLE_POWER_KW = 0.0
FRIDGE_PRIORITY = 5
FRIDGE_COOLING_COEFFICIENT = 0.1
FRIDGE_TEMP_UPDATE_RATE_ON = 0.15
FRIDGE_TEMP_UPDATE_RATE_OFF = 0.05

# Washing Machine
WASHING_MACHINE_THRESHOLD = 16
WASHING_MACHINE_CYCLE_DURATION_MINUTES = 60
WASHING_MACHINE_PER_CYCLE = 10
WASHING_MACHINE_ACCUMULATION_RATE = 1
WASHING_MACHINE_PRICE_SENSITIVITY = 0
WASHING_MACHINE_ACTIVE_POWER_KW = 0.5
WASHING_MACHINE_IDLE_POWER_KW = 0.0
WASHING_MACHINE_WAITING_BONUS_DIVIDER = 3
WASHING_MACHINE_PRIORITY_THRESHOLDS = [20, 19, 18, 17] # Counts for priority 5, 4, 3, 2